name: Stock checker

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install playwright resend
          playwright install chromium

      - name: Run script
        run: python stock_alert.py
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
